### PR TITLE
teleporter improved improved -> teleporter improved

### PR DESCRIPTION
**Pull request by minertestdude**
- simplification of the structure from modpack into regular mod
- fix for "pos" errors on game reload
- two 16x16 texture replacements
- teleport sound playing
- MineClone2 game compatibility

### CODE REVIEW

**Comment by r4nd0m6uy** [comment]
Thanks for the contribution, I'm glad to see that someone is enjoying my mode!

Unfortunately, I have never really maintained this project and don't have time to test more in details but looks good at first glance and will merge it.

That is also why you are welcome to take over the project if you feel like it :tongue:

**Comment by r4nd0m6uy** [comment]
Arff sorry wrong button, it will be merged :tongue: !

**Comment by minertestdude** [comment]
@r4nd0m6uy  Hey! Thank you! I am not sure how do you switch ownership, but I won't resist.

I am thinking actually it would be better to submit the mod to "minetest-mods" owner, that is project to host multiple small unmaintained mods. I will commit all my small changes to that project instead, but I want to kindly ask you to reassign to them!

Thank you very much.
I am also sending latest small commit that adds few improvements.

**Comment by r4nd0m6uy** [comment]
I can transfer the project in the setting pages, as long as you keep the credits, do whatever you want.

I was told to put this mod there, I guess it will make easier for poeple to find it. As you wish!

**Comment by r4nd0m6uy** [comment]
Arff it doesn't work:
minertestdude/teleporter already exists

Could you remove, move it so you can own it?

**Comment by minertestdude** [comment]
Sure, since you merged.
I will of course keep the credits, its about repository - not copyrights.  So far my work has been more of cosmetic, compared to yours. ;)

PS: I am trying to pull some mods to Mineclone2, maybe it could interest you at some time. :) https://forum.minetest.net/viewtopic.php?f=47&t=20935

**Pull request closed without merging**
